name: Check TS + ESLint

on:
  pull_request:
    branches:
      - main
      - prod

permissions: 
  issues: write
  pull-requests: write

jobs:
  typescript-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: corepack enable pnpm

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript Check
        id: tsc
        run: |
          pnpm --silent --use-stderr tsc --noEmit > tsc_output.txt 2>&1 || true

      - name: Run ESLint
        id: eslint
        run: |
          pnpm --silent --use-stderr lint --max-warnings=0 > eslint_output.txt 2>&1 || true

      - name: Comment TS + ESLint Results on PR
        uses: actions/github-script@v6
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const path = require("path");
            require('./.github/workflows/check_tsc.cjs')({ github, context, root: path.resolve("./") });
