name: Vite App CI/CD

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Enable corepack
      run: |
        corepack enable

    - name: Cache pnpm store
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: |
        pnpm install

    - name: Build Vite App
      run: |
        pnpm build
        ls -al dist/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vite-build
        path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: vite-build
        path: dist

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        ssh-keyscan -t ed25519 ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        chmod 644 ~/.ssh/known_hosts

    - name: Upload artifacts to VPS
      run: |
        scp -i ~/.ssh/id_ed25519 -r ./dist/* ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}

    - name: Verify deployment
      run: |
        curl -H "Cache-Control: no-cache" -I https://mairech.cc
